---
title: "Paper wellfare Brazil"
output: html_document
date: "2024-02-19"
---

```{r setup, include=FALSE}
library(tidyverse)
library(colorspace)
library(patchwork)
library(sf)
library(ggrepel)


knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)

dados_estados_paper <- readRDS("~/github/population_welfare/dados_estados_paper.RDS")
mapa_estados <- readRDS("~/Github/population_welfare/mapa_estados.rds")

const_u<- 4.87 #Confomre valores vindo do paper
const_c<- 38000 #Confomre valores vindo do paper

```


```{r cars}

dados_calculo_paper<-
 dados_estados_paper %>%
  group_by(sigla_uf) %>%
  mutate(gN =  ((populacao/lag(populacao))-1) *100,
         gC = (((consumo_per_capita) /lag(consumo_per_capita))-1)*100,
         vc = const_u + log(consumo_per_capita/const_c),
         gN_vc = gN * vc,
         glambda = gN_vc + gC,
         decada = case_when(
           between(ano,2003, 2010) ~ "2003 - 2010",
           between(ano,2011, 2019) ~ "2011 - 2019") 
         ) %>%
  ungroup() %>%
  filter(ano>2002) %>%
  select( sigla_uf, ano, populacao, gN, consumo_uf, consumo_per_capita, gC, vc, gN_vc,glambda,decada ) 


```

```{r}
dados_calculo_paper_agregado<-
dados_calculo_paper%>%
  summarise(
    media_gc = mean(gC, na.rm = TRUE),
    media_gN = mean(gN, na.rm = TRUE),
    media_vc = mean(const_u + log(consumo_per_capita/const_c), na.rm = TRUE),
    media_gN_vc = mean(gN_vc, na.rm = TRUE), # media_gN * media_vc,
    glambda_periodo = media_gN_vc + media_gc ,
    pop_share = (media_gN_vc/glambda_periodo)*100,
    .by = c(sigla_uf, decada)
  )


dados_calculo_paper_agregado %>%
  select(sigla_uf,
         decada,
         glambda_periodo,
         media_gc,
         media_gN,
         media_vc,
         media_gN_vc,
         pop_share) %>%
  arrange(decada, desc(glambda_periodo))
```


```{r}

dados_calculo_paper_agregado %>%
      rename(abbrev_state = sigla_uf) %>%
inner_join(mapa_estados)%>%
  ggplot(aes(geometry = geom))+
  geom_sf(aes( fill=glambda_periodo)) +
  scale_fill_continuous_sequential(palette="Heat") +
  facet_wrap(decada~.) +
  theme_void() +
  labs(
    title = "Crescimento do bem estar equivalente ao consumo",
    fill = "(%)"
  )
  
  
  

```

```{r}

graf1<-
dados_calculo_paper_agregado %>%
  filter(decada == "2003 - 2010") %>%
  mutate(sigla_uf = reorder(sigla_uf, glambda_periodo )) %>%
  ggplot(aes(x=glambda_periodo, y= sigla_uf)) +
  xlim(c(0,12))+
  geom_col() +
  geom_text(aes(label=round(glambda_periodo,1)),size=2.8, hjust = -0.1)+
  facet_wrap(decada~.) +
  theme_light() +
  theme(
    panel.grid =  element_blank() 
  ) +
  labs(
    title = str_wrap("Crescimento do bem estar equivalente ao consumo (%)",30),
    x= "",
    y=""
  )

graf2<-
dados_calculo_paper_agregado %>%
  filter(decada == "2011 - 2019") %>%
  mutate(sigla_uf = reorder(sigla_uf, glambda_periodo )) %>%
  ggplot(aes(x=glambda_periodo, y= sigla_uf)) +
  geom_col() +
  geom_text(aes(label=round(glambda_periodo,1)),size=2.8, hjust = -0.1)+
  xlim(c(0,12))+
  facet_wrap(decada~.) +
  theme_light() +
  theme(
    panel.grid =  element_blank()
  ) +
  labs(
    x= "",
    y=""
  )

graf1 + graf2 

  
```

```{r}

graf1<-
dados_calculo_paper_agregado %>%
  filter(decada == "2003 - 2010") %>%
  mutate(sigla_uf = reorder(sigla_uf, glambda_periodo )) %>%
  pivot_longer(cols=3:8, names_to = "componente", values_to = "valor") %>%  
  filter(componente %in% c("media_gc","media_gN_vc")) %>%
  mutate(componente = ifelse(componente == "media_gc", "consumo", "população" )) %>%
  ggplot(aes(x=valor, y= sigla_uf, fill= componente)) +
  scale_fill_discrete_qualitative(palette = "Cold")+
  geom_col(show.legend = FALSE) +
  geom_text(aes(label=round(valor,1) ,hjust= ifelse(valor>0, -0.1,1.1)), size=2.5 , position = position_stack(vjust = 0.8)) +
  facet_wrap(decada ~ .) +
  theme_light() +
  theme(panel.grid = element_blank())  +
  labs(
    title = str_wrap("Crescimento do bem estar equivalente ao consumo (%)",30),
    x= "",
    y=""
  )

graf2<-
dados_calculo_paper_agregado %>%
  filter(decada == "2011 - 2019") %>%
  mutate(sigla_uf = reorder(sigla_uf, glambda_periodo )) %>%
  pivot_longer(cols=3:8, names_to = "componente", values_to = "valor") %>%  
  filter(componente %in% c("media_gc","media_gN_vc")) %>%
  mutate(componente = ifelse(componente == "media_gc", "consumo", "população" )) %>%
  ggplot(aes(x=valor, y= sigla_uf, fill= componente)) +
  scale_fill_discrete_qualitative(palette = "Cold")+
  geom_col() +
  geom_text(aes(label=round(valor,1) ,hjust= ifelse(valor>0, -0.1,1.1)), size=2.5 , position = position_stack(vjust = 0.8)) +
  facet_wrap(decada ~ .) +
  theme_light() +
  theme(panel.grid = element_blank(),
        legend.position = "bottom") +
  labs(
    x = "",
    y = ""
  )





graf1 + graf2 

```



```{r}

estados<- c("DF","PI","AM","RS","SP","ES")

ultima_posicao<-
  dados_calculo_paper %>%
  filter(sigla_uf %in% estados ,
         ano %in% c(2003,2019)) %>%
  arrange(ano)


dados_calculo_paper %>%
  filter(sigla_uf %in% estados) %>%
  ggplot(aes(x=as.factor(ano), y=vc)) +
  geom_line(aes(group = sigla_uf, color = sigla_uf), show.legend = FALSE, size =1) +
  geom_text(data= ultima_posicao, aes(label = sigla_uf, color = sigla_uf), hjust = c(rep(1,NROW(estados)),rep(-0.1,NROW(estados))), show.legend = FALSE)+
  scale_color_discrete_qualitative(palette = "Dark 3") +
  theme_light() +
  theme(
    panel.grid =  element_blank()
  ) +
  labs(
    x= "",
    y= "valor da vida per capita",
    title = "Evolução do valor da vida per capita"
  )
  
```

```{r}

dados_calculo_paper %>%
  filter(sigla_uf %in% estados) %>%
  ggplot(aes(x=as.factor(ano), y=gN)) +
  geom_col(aes(fill = sigla_uf), show.legend = FALSE) +
  #geom_line(aes(group = sigla_uf, color = sigla_uf), show.legend = FALSE, size =1) +
  #geom_text(data= ultima_posicao, aes(label = sigla_uf, color = sigla_uf), hjust = c(rep(1,NROW(estados)),rep(-0.1,NROW(estados))), show.legend = FALSE) +
  scale_fill_discrete_qualitative(palette = "Dark 3") +
  theme_light() +
  theme(
    panel.grid =  element_blank(),
    axis.text.x = element_text(angle = 90)
  ) +
  labs(
    x= "",
    y= "Variação da população em (%)",
    title = "Evolução da variação da população"
  ) +
  facet_wrap(sigla_uf~.)
 

```

```{r}
dados_calculo_paper %>%
  filter(sigla_uf %in% estados) %>%
  ggplot(aes(x=as.factor(ano), y=gC))  +
  geom_col(aes(fill=sigla_uf), show.legend = FALSE) +
  #geom_line(aes(group = sigla_uf, color = sigla_uf), show.legend = FALSE, size =1) +
  #geom_text(data= ultima_posicao, aes(label = sigla_uf, color = sigla_uf), hjust = c(rep(1,NROW(estados)),rep(-0.1,NROW(estados))), show.legend = FALSE) +
  scale_fill_discrete_qualitative(palette = "Dark 3") +
  theme_light() +
  theme(
    panel.grid =  element_blank(),
    axis.text.x = element_text(angle = 90)
  ) +
  labs(
    x= "",
    y= "Variação do consumo per capita em (%)",
    title = "Evolução da variação do consumo per capita"
  )+
  facet_wrap(sigla_uf~.)
```

